import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { fileURLToPath } from 'node:url'
import { builtinModules } from 'node:module'

const external: string[] = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  ...builtinModules
]

const banner: string = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD (via VITE)
if you want to view the source, please visit the github repository of this plugin
*/`

export default defineConfig(({ mode }) => {
  const prod = mode == 'production'

  return {
    plugins: [vue()],
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
    },
    build: {
      lib: {
        entry: 'src/main.ts',
        name: 'ObsidianNoteflakes',
        fileName: () => 'main.js',
        formats: ['cjs'],
      },
      rollupOptions: {
        external,
        output: {
          exports: 'named',
          banner,
          assetFileNames: (assetInfo) => {
            if (assetInfo.names[0].endsWith('.css')) return 'styles.css'
            return '[name][extname]'
          },
        },
        treeshake: true,
      },
      outDir: '.',
      emptyOutDir: false,
      target: 'es2018',
      minify: prod,
      sourcemap: prod ? false : 'inline',
    },
  }
})
