import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import banner from 'vite-plugin-banner'
import { fileURLToPath } from 'node:url'
import { builtinModules } from 'node:module'

const external: string[] = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  ...builtinModules
]

const bannerContent: string = `/*!
THIS IS A GENERATED/BUNDLED FILE BY VITE
Please visit the github repository of this plugin for the source file:
https://github.com/idlist/flakepiles
*/`

export default defineConfig(({ mode }) => {
  const prod = mode == 'production'

  const define = {}
  if (prod) {
    define['process.env.NODE_ENV'] = '"production"'
  }

  return {
    plugins: [
      vue(),
      banner(bannerContent)
    ],
    define,
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
    },
    build: {
      target: 'es2018',
      outDir: '.',
      sourcemap: prod ? false : 'inline',
      rollupOptions: {
        external,
      },
      lib: {
        entry: 'src/main.ts',
        fileName: () => 'main.js',
        formats: ['cjs'],
        cssFileName: 'styles'
      },
      minify: prod,
      emptyOutDir: false,
    },
  }
})
